In [104]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sn
from sklearn.model_selection import train_test_split
from sklearn.decomposition import PCA
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [5]:
hlt = pd.read_csv("health_data.csv")
hlt.head()

,avganncount,avgdeathsperyear,target_deathrate,incidencerate,medincome,popest2015,povertypercent,studypercap,binnedinc,medianage,...,pctprivatecoveragealone,pctempprivcoverage,pctpubliccoverage,pctpubliccoveragealone,pctwhite,pctblack,pctasian,pctotherrace,pctmarriedhouseholds,birthrate
0,1397.0,469,164.9,489.8,61898,260131,11.2,499.748204,"(61494.5, 125635]",39.3,...,NaN,41.6,32.9,14.0,81.780529,2.594728,4.821857,1.843479,52.856076,6.118831
1,173.0,70,161.3,411.6,48127,43269,18.6,23.111234,"(48021.6, 51046.4]",33.0,...,53.8,43.6,31.1,15.3,89.228509,0.969102,2.246233,3.741352,45.372500,4.333096
2,102.0,50,174.7,349.7,49348,21026,14.6,47.560164,"(48021.6, 51046.4]",45.0,...,43.5,34.9,42.1,21.1,90.922190,0.739673,0.465898,2.747358,54.444868,3.729488
3,427.0,202,194.8,430.4,44243,75882,17.1,342.637253,"(42724.4, 45201]",42.8,...,40.3,35.0,45.3,25.0,91.744686,0.782626,1.161359,1.362643,51.021514,4.603841
4,57.0,26,144.4,350.1,49955,10321,12.5,0.000000,"(48021.6, 51046.4]",48.3,...,43.9,35.1,44.0,22.7,94.104024,0.270192,0.665830,0.492135,54.027460,6.796657

In [7]:
hlt.isna().sum()

avganncount                   0
avgdeathsperyear              0
target_deathrate              0
incidencerate                 0
medincome                     0
popest2015                    0
povertypercent                0
studypercap                   0
binnedinc                     0
medianage                     0
medianagemale                 0
medianagefemale               0
geography                     0
percentmarried                0
pctnohs18_24                  0
pcths18_24                    0
pctsomecol18_24            2285
pctbachdeg18_24               0
pcths25_over                  0
pctbachdeg25_over             0
pctemployed16_over          152
pctunemployed16_over          0
pctprivatecoverage            0
pctprivatecoveragealone     609
pctempprivcoverage            0
pctpubliccoverage             0
pctpubliccoveragealone        0
pctwhite                      0
pctblack                      0
pctasian                      0
pctotherrace                  0
pctmarriedhouseholds          0
birthrate                     0
dtype: int64

In [29]:
hlt_records_dropped = hlt.dropna(axis=0, how='any')
hlt_records_dropped.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 591 entries, 1 to 3046
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   avganncount              591 non-null    float64
 1   avgdeathsperyear         591 non-null    int64
 2   target_deathrate         591 non-null    float64
 3   incidencerate            591 non-null    float64
 4   medincome                591 non-null    int64
 5   popest2015               591 non-null    int64
 6   povertypercent           591 non-null    float64
 7   studypercap              591 non-null    float64
 8   binnedinc                591 non-null    object
 9   medianage                591 non-null    float64
 10  medianagemale            591 non-null    float64
 11  medianagefemale          591 non-null    float64
 12  geography                591 non-null    object
 13  percentmarried           591 non-null    float64
 14  pctnohs18_24             591 non-null    float64
 15  pcths18_24               591 non-null    float64
 16  pctsomecol18_24          591 non-null    float64
 17  pctbachdeg18_24          591 non-null    float64
 18  pcths25_over             591 non-null    float64
 19  pctbachdeg25_over        591 non-null    float64
 20  pctemployed16_over       591 non-null    float64
 21  pctunemployed16_over     591 non-null    float64
 22  pctprivatecoverage       591 non-null    float64
 23  pctprivatecoveragealone  591 non-null    float64
 24  pctempprivcoverage       591 non-null    float64
 25  pctpubliccoverage        591 non-null    float64
 26  pctpubliccoveragealone   591 non-null    float64
 27  pctwhite                 591 non-null    float64
 28  pctblack                 591 non-null    float64
 29  pctasian                 591 non-null    float64
 30  pctotherrace             591 non-null    float64
 31  pctmarriedhouseholds     591 non-null    float64
 32  birthrate                591 non-null    float64
dtypes: float64(28), int64(3), object(2)
memory usage: 157.0+ KB

In [31]:
hlt_records_dropped.isna().sum()

avganncount                0
avgdeathsperyear           0
target_deathrate           0
incidencerate              0
medincome                  0
popest2015                 0
povertypercent             0
studypercap                0
binnedinc                  0
medianage                  0
medianagemale              0
medianagefemale            0
geography                  0
percentmarried             0
pctnohs18_24               0
pcths18_24                 0
pctsomecol18_24            0
pctbachdeg18_24            0
pcths25_over               0
pctbachdeg25_over          0
pctemployed16_over         0
pctunemployed16_over       0
pctprivatecoverage         0
pctprivatecoveragealone    0
pctempprivcoverage         0
pctpubliccoverage          0
pctpubliccoveragealone     0
pctwhite                   0
pctblack                   0
pctasian                   0
pctotherrace               0
pctmarriedhouseholds       0
birthrate                  0
dtype: int64

In [34]:
hlt_records_dropped.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 591 entries, 1 to 3046
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   avganncount              591 non-null    float64
 1   avgdeathsperyear         591 non-null    int64
 2   target_deathrate         591 non-null    float64
 3   incidencerate            591 non-null    float64
 4   medincome                591 non-null    int64
 5   popest2015               591 non-null    int64
 6   povertypercent           591 non-null    float64
 7   studypercap              591 non-null    float64
 8   binnedinc                591 non-null    object
 9   medianage                591 non-null    float64
 10  medianagemale            591 non-null    float64
 11  medianagefemale          591 non-null    float64
 12  geography                591 non-null    object
 13  percentmarried           591 non-null    float64
 14  pctnohs18_24             591 non-null    float64
 15  pcths18_24               591 non-null    float64
 16  pctsomecol18_24          591 non-null    float64
 17  pctbachdeg18_24          591 non-null    float64
 18  pcths25_over             591 non-null    float64
 19  pctbachdeg25_over        591 non-null    float64
 20  pctemployed16_over       591 non-null    float64
 21  pctunemployed16_over     591 non-null    float64
 22  pctprivatecoverage       591 non-null    float64
 23  pctprivatecoveragealone  591 non-null    float64
 24  pctempprivcoverage       591 non-null    float64
 25  pctpubliccoverage        591 non-null    float64
 26  pctpubliccoveragealone   591 non-null    float64
 27  pctwhite                 591 non-null    float64
 28  pctblack                 591 non-null    float64
 29  pctasian                 591 non-null    float64
 30  pctotherrace             591 non-null    float64
 31  pctmarriedhouseholds     591 non-null    float64
 32  birthrate                591 non-null    float64
dtypes: float64(28), int64(3), object(2)
memory usage: 157.0+ KB

In [36]:
hlt_records_dropped.describe()

,avganncount,avgdeathsperyear,target_deathrate,incidencerate,medincome,popest2015,povertypercent,studypercap,medianage,medianagemale,...,pctprivatecoveragealone,pctempprivcoverage,pctpubliccoverage,pctpubliccoveragealone,pctwhite,pctblack,pctasian,pctotherrace,pctmarriedhouseholds,birthrate
count,591.000000,591.000000,591.000000,591.000000,591.000000,5.910000e+02,591.000000,591.000000,591.000000,591.000000,...,591.000000,591.000000,591.000000,591.000000,591.000000,591.000000,591.000000,591.000000,591.000000,591.000000
mean,682.316495,199.411168,179.090863,452.657990,47032.851100,1.145526e+05,16.723181,122.729567,45.985787,39.573266,...,48.749069,41.534687,36.193063,19.203215,84.224532,8.727607,1.183705,1.921294,51.318223,5.739657
std,1977.289390,708.330454,27.273580,54.381212,11405.103542,5.043527e+05,6.219356,357.586595,47.697553,5.118305,...,9.920562,9.544078,7.571871,5.960506,15.450720,13.582028,1.969232,3.391412,6.240708,1.899942
min,6.000000,3.000000,94.400000,234.000000,23047.000000,8.290000e+02,4.800000,0.000000,23.200000,23.700000,...,23.700000,16.300000,14.800000,2.600000,11.008762,0.000000,0.000000,0.000000,24.024634,0.413223
25%,87.000000,30.000000,161.350000,425.250000,39305.000000,1.232850e+04,12.000000,0.000000,38.200000,36.600000,...,41.900000,34.750000,30.950000,14.950000,78.083708,0.681788,0.267913,0.284278,48.105663,4.606546
50%,183.000000,64.000000,177.900000,453.549422,45235.000000,2.775500e+04,15.600000,0.000000,40.900000,39.500000,...,49.000000,41.600000,36.500000,18.700000,90.238859,2.450805,0.569827,0.755216,51.673640,5.497771
75%,542.000000,131.000000,195.400000,481.550000,52686.500000,6.621700e+04,19.900000,60.953380,43.600000,42.250000,...,55.900000,48.550000,40.700000,22.900000,95.266834,11.395684,1.197193,2.151791,55.311860,6.706986
max,38150.000000,14010.000000,293.900000,1014.200000,97279.000000,1.017029e+07,45.100000,3657.320182,508.800000,58.500000,...,76.600000,68.800000,62.200000,41.400000,100.000000,84.866024,23.238107,37.610994,71.703057,17.877095

In [41]:
hlt_records_dropped = hlt_records_dropped.drop_duplicates()
hlt_records_dropped

,avganncount,avgdeathsperyear,target_deathrate,incidencerate,medincome,popest2015,povertypercent,studypercap,binnedinc,medianage,...,pctprivatecoveragealone,pctempprivcoverage,pctpubliccoverage,pctpubliccoveragealone,pctwhite,pctblack,pctasian,pctotherrace,pctmarriedhouseholds,birthrate
1,173.000000,70,161.3,411.600000,48127,43269,18.6,23.111234,"(48021.6, 51046.4]",33.0,...,53.8,43.6,31.1,15.3,89.228509,0.969102,2.246233,3.741352,45.372500,4.333096
3,427.000000,202,194.8,430.400000,44243,75882,17.1,342.637253,"(42724.4, 45201]",42.8,...,40.3,35.0,45.3,25.0,91.744686,0.782626,1.161359,1.362643,51.021514,4.603841
4,57.000000,26,144.4,350.100000,49955,10321,12.5,0.000000,"(48021.6, 51046.4]",48.3,...,43.9,35.1,44.0,22.7,94.104024,0.270192,0.665830,0.492135,54.027460,6.796657
7,146.000000,71,183.6,404.000000,40189,20848,17.8,0.000000,"(37413.8, 40362.7]",51.7,...,33.1,25.9,50.9,24.1,89.406636,0.305159,1.889077,2.286268,48.967033,5.889179
14,2265.000000,901,171.0,440.700000,50083,490945,16.3,462.373586,"(48021.6, 51046.4]",37.2,...,50.6,42.5,36.5,21.4,89.038167,1.827041,2.315986,1.033625,48.188377,5.355836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3033,1962.667684,7,209.6,453.549422,45353,1843,11.4,0.000000,"(45201, 48021.6]",45.7,...,52.7,43.9,32.2,9.2,97.960199,0.000000,0.547264,0.995025,57.780612,4.664723
3034,1962.667684,85,184.4,453.549422,45180,35788,15.0,1900.078239,"(42724.4, 45201]",38.2,...,52.3,46.2,34.4,17.4,87.718617,3.168048,1.610355,1.893068,50.730567,7.404551
3043,1962.667684,43,150.1,453.549422,48609,37118,18.8,377.175494,"(48021.6, 51046.4]",30.4,...,53.3,48.6,28.8,17.7,75.706245,2.326771,4.044920,14.130288,52.007937,8.186470
3044,1962.667684,46,153.9,453.549422,51144,34536,15.0,1968.959926,"(51046.4, 54545.6]",30.9,...,52.6,47.8,26.6,16.8,87.961629,2.313188,1.316472,5.680705,55.153949,7.809192
3046,1962.667684,48,213.6,453.549422,41193,37030,13.9,0.000000,"(40362.7, 42724.4]",26.2,...,60.3,22.9,25.1,12.6,70.098132,16.590100,3.177753,1.356457,56.040242,8.981723

In [85]:
df1 = hlt_records_dropped.drop(columns=['binnedinc', 'geography'], axis=1)
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 591 entries, 1 to 3046
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   avganncount              591 non-null    float64
 1   avgdeathsperyear         591 non-null    int64
 2   target_deathrate         591 non-null    float64
 3   incidencerate            591 non-null    float64
 4   medincome                591 non-null    int64
 5   popest2015               591 non-null    int64
 6   povertypercent           591 non-null    float64
 7   studypercap              591 non-null    float64
 8   medianage                591 non-null    float64
 9   medianagemale            591 non-null    float64
 10  medianagefemale          591 non-null    float64
 11  percentmarried           591 non-null    float64
 12  pctnohs18_24             591 non-null    float64
 13  pcths18_24               591 non-null    float64
 14  pctsomecol18_24          591 non-null    float64
 15  pctbachdeg18_24          591 non-null    float64
 16  pcths25_over             591 non-null    float64
 17  pctbachdeg25_over        591 non-null    float64
 18  pctemployed16_over       591 non-null    float64
 19  pctunemployed16_over     591 non-null    float64
 20  pctprivatecoverage       591 non-null    float64
 21  pctprivatecoveragealone  591 non-null    float64
 22  pctempprivcoverage       591 non-null    float64
 23  pctpubliccoverage        591 non-null    float64
 24  pctpubliccoveragealone   591 non-null    float64
 25  pctwhite                 591 non-null    float64
 26  pctblack                 591 non-null    float64
 27  pctasian                 591 non-null    float64
 28  pctotherrace             591 non-null    float64
 29  pctmarriedhouseholds     591 non-null    float64
 30  birthrate                591 non-null    float64
dtypes: float64(28), int64(3)
memory usage: 147.8 KB

In [86]:
y =df1 ["target_deathrate"]
x = df1.drop(columns=["target_deathrate"])

In [87]:
x

,avganncount,avgdeathsperyear,incidencerate,medincome,popest2015,povertypercent,studypercap,medianage,medianagemale,medianagefemale,...,pctprivatecoveragealone,pctempprivcoverage,pctpubliccoverage,pctpubliccoveragealone,pctwhite,pctblack,pctasian,pctotherrace,pctmarriedhouseholds,birthrate
1,173.000000,70,411.600000,48127,43269,18.6,23.111234,33.0,32.2,33.7,...,53.8,43.6,31.1,15.3,89.228509,0.969102,2.246233,3.741352,45.372500,4.333096
3,427.000000,202,430.400000,44243,75882,17.1,342.637253,42.8,42.2,43.4,...,40.3,35.0,45.3,25.0,91.744686,0.782626,1.161359,1.362643,51.021514,4.603841
4,57.000000,26,350.100000,49955,10321,12.5,0.000000,48.3,47.8,48.9,...,43.9,35.1,44.0,22.7,94.104024,0.270192,0.665830,0.492135,54.027460,6.796657
7,146.000000,71,404.000000,40189,20848,17.8,0.000000,51.7,50.8,52.5,...,33.1,25.9,50.9,24.1,89.406636,0.305159,1.889077,2.286268,48.967033,5.889179
14,2265.000000,901,440.700000,50083,490945,16.3,462.373586,37.2,35.7,38.7,...,50.6,42.5,36.5,21.4,89.038167,1.827041,2.315986,1.033625,48.188377,5.355836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3033,1962.667684,7,453.549422,45353,1843,11.4,0.000000,45.7,43.8,49.2,...,52.7,43.9,32.2,9.2,97.960199,0.000000,0.547264,0.995025,57.780612,4.664723
3034,1962.667684,85,453.549422,45180,35788,15.0,1900.078239,38.2,36.5,40.0,...,52.3,46.2,34.4,17.4,87.718617,3.168048,1.610355,1.893068,50.730567,7.404551
3043,1962.667684,43,453.549422,48609,37118,18.8,377.175494,30.4,29.3,31.4,...,53.3,48.6,28.8,17.7,75.706245,2.326771,4.044920,14.130288,52.007937,8.186470
3044,1962.667684,46,453.549422,51144,34536,15.0,1968.959926,30.9,30.5,31.2,...,52.6,47.8,26.6,16.8,87.961629,2.313188,1.316472,5.680705,55.153949,7.809192
3046,1962.667684,48,453.549422,41193,37030,13.9,0.000000,26.2,25.5,27.0,...,60.3,22.9,25.1,12.6,70.098132,16.590100,3.177753,1.356457,56.040242,8.981723

In [88]:
y

1       161.3
3       194.8
4       144.4
7       183.6
14      171.0
        ...
3033    209.6
3034    184.4
3043    150.1
3044    153.9
3046    213.6
Name: target_deathrate, Length: 591, dtype: float64

In [89]:
df1['target_deathrate'].value_counts()

169.9    4
172.5    4
185.1    4
190.7    4
187.2    3
        ..
140.8    1
124.1    1
217.4    1
164.9    1
213.6    1
Name: target_deathrate, Length: 449, dtype: int64

In [90]:
X_train,X_test,y_train,y_test=train_test_split(x, y, test_size=0.2,random_state=42)

In [91]:
print('shape of training set: ',X_train.shape)
print('shape of test set: ',X_test.shape)

shape of training set:  (472, 30)
shape of test set:  (119, 30)

In [92]:
model = LinearRegression()

In [93]:
model.fit(X_train,y_train)

LinearRegression()

In [97]:
print(model.intercept_)

2590.3758282216195

In [99]:
print(model.coef_)

[-3.31901001e-03  8.48159836e-03  1.47068701e-01  2.58799125e-04
  9.65132157e-07 -4.21728690e-01 -4.10975061e-04 -1.57911882e-02
 -1.20453637e+00  5.06218652e-01  2.55881172e+00 -2.40063478e+01
 -2.38830875e+01 -2.39241940e+01 -2.47495031e+01  7.14152135e-01
 -7.75443515e-01 -1.26704034e+00  7.23123338e-01  3.40313580e-01
 -6.42001606e-01  4.30568958e-01 -1.70357523e+00  2.16859749e+00
  2.22398255e-01  2.59894458e-01  2.33989207e-01 -8.62006270e-01
 -2.83403803e+00 -8.94193874e-01]

In [101]:
pred=model.predict(X_test)

In [106]:
predictions = pred.reshape(-1,1)

In [108]:
print('MSE : ', mean_squared_error(y_test,predictions))
print('RMSE : ', np.sqrt(mean_squared_error(y_test,predictions)))

MSE :  545.0064371066992
RMSE :  23.34537292712839